# PyTorch 
a library to build and train neural networks.

It mainly gives you 3 superpowers:
1. Tensors → like NumPy arrays but for deep learning
2. Autograd → automatic gradient calculation (backprop)
3. Neural Network tools → layers, loss functions, optimizers

In [20]:
import torch

# Create Tensor
x = torch.tensor([1,2,3,4])  
x

tensor([1, 2, 3, 4])

In [21]:
# Check Shape
x.shape

torch.Size([4])

In [22]:
# Create a 2D Tensor (Matrix)

twoD = torch.tensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
]) 

twoD

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [23]:
twoD.shape  # Means → 4 rows, 2 columns

torch.Size([4, 2])

In [24]:
# Random Tensors (Used in Neural Networks)

R = torch.rand(3,4)   # Creates a 3×4 tensor with random numbers between 0 and 1.
R

tensor([[0.8513, 0.9815, 0.0967, 0.3665],
        [0.6521, 0.0226, 0.1485, 0.0740],
        [0.1896, 0.1137, 0.8555, 0.6984]])

In [25]:
# Zeros and Ones

zeros = torch.zeros(2,3)
ones = torch.ones(2,3)

print(zeros)
print(50*"=")
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [26]:
# Tensor Math (Like NumPy)
# element-wise addition, multiplication

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a+b)
print(50*"=")
print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [27]:
# GPU (Makes Deep Learning Fast)

print(torch.cuda.is_available())

# If True, you can move tensor to GPU:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = torch.tensor([1, 2, 3]).to(device)
print(x,"device: ",device)


False
tensor([1, 2, 3]) device:  cpu


# 🎯 Assignment 1
Write code that:
1. Creates a random tensor of shape (5, 3)
2. Prints:
    - The tensor
    - Its shape
3. Creates another random tensor of same shape
4. Adds them
5. Moves result to GPU (if available)

In [28]:
r1 = torch.rand(5,3)
print(r1)
r1.shape

tensor([[0.5927, 0.9789, 0.5670],
        [0.9655, 0.9555, 0.8922],
        [0.6773, 0.6253, 0.9931],
        [0.3056, 0.8041, 0.1652],
        [0.2000, 0.9185, 0.6720]])


torch.Size([5, 3])

In [29]:
r2 = torch.rand(5,3)
r2

tensor([[0.1168, 0.2076, 0.0989],
        [0.1573, 0.2221, 0.6020],
        [0.4740, 0.7334, 0.2192],
        [0.9572, 0.0553, 0.9345],
        [0.1558, 0.8586, 0.7008]])

In [30]:
r1+r2

tensor([[0.7095, 1.1866, 0.6659],
        [1.1228, 1.1776, 1.4942],
        [1.1513, 1.3586, 1.2122],
        [1.2628, 0.8594, 1.0996],
        [0.3557, 1.7771, 1.3728]])

# 🧩 LESSON 2 — AUTOGRAD (How Neural Networks Learn)
Neural networks learn by adjusting weights using gradients.

Normally, you'd have to manually calculate derivatives like:
- 𝑦 = 𝑥^2 + 2𝑥 + 1            
- 𝑑𝑦/dx = 2𝑥 + 2

But PyTorch says:
“Relax. I got this.”

That system = Autograd

In [31]:
# Create a Tensor That Tracks Gradients

import torch

x = torch.tensor(5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [32]:
# Define a Function
y = x**2 + 2*x + 1
print(y)

tensor(36., grad_fn=<AddBackward0>)


In [33]:
# Backpropagation
y.backward()    # PyTorch, compute dy/dx”

In [34]:
# Get the Gradient

print(x.grad)

tensor(12.)


# 🎯 Assignment 2
Write code that:
1. Creates a tensor x = 3.0 with gradient tracking
2. Define:
- 𝑦 = 4𝑥^2 + 3𝑥
3. Call .backward()
4. Print gradient

Then verify manually.

In [35]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [36]:
# function
y = 4*x**2+3*x
print(y)

tensor(45., grad_fn=<AddBackward0>)


In [37]:
y.backward()

In [38]:
x.grad

tensor(27.)

# 🧩 LESSON 3 — Your First Neural Network
We will make a model that learns this line:
- 𝑦 = 2𝑥 + 1

If the model learns correctly → it discovers slope = 2 and bias = 1 by itself.

built : x → Linear → y


In [39]:
import torch
import torch.nn as nn            # neural network tools 
import torch.optim as optim      # optimizers (how weights update)

In [40]:
# Create Model
model = nn.Linear(1,1)
model

Linear(in_features=1, out_features=1, bias=True)

In [41]:
# Create Data
x = torch.tensor([
    [1.0], [2.0], [3.0],[4.0]
])

y = torch.tensor([
    [3.0], [5.0], [7.0], [9.0]     # y = 2x + 1
])

In [42]:
# Loss Function
loss_fn = nn.MSELoss()

In [43]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [44]:
for epoch in range(1000):
    pred = model(x)
    loss = loss_fn(pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [45]:
print("Weight", model.weight.item())
print("Bias:", model.bias.item())

Weight 1.9916598796844482
Bias: 1.0245212316513062


# 🧩 LESSON 5 — Multi-Layer Neural Network + Activation
built : x → Linear → ReLU → Linear → y


In [46]:
import torch
import torch.nn as nn
import torch.optim as optim

In [47]:
# Create Non-Linear Dataset
# We’ll train the model om: y=x^2

x = torch.linspace(-5, 5, 100).view(-1,1)
y = x**2

In [48]:
x.shape

torch.Size([100, 1])

In [49]:
# Build Multi-Layer Model

model = nn.Sequential(
    nn.Linear(1, 10),  # input → hidden
    nn.ReLU(),         # activation
    nn.Linear(10, 1)   # hidden → output
)

In [50]:
# Loss & Optimizer

loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [51]:
# Training Loop

for epoch in range(2000):
    pred = model(x)
    loss = loss_fn(pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 200 ==0:
        print(f"Epoch {epoch}, Loss: {loss.item}:.4f")

Epoch 0, Loss: <built-in method item of Tensor object at 0x0000016EBC9DF660>:.4f
Epoch 200, Loss: <built-in method item of Tensor object at 0x0000016EBC9F5090>:.4f
Epoch 400, Loss: <built-in method item of Tensor object at 0x0000016EBC9DF7F0>:.4f
Epoch 600, Loss: <built-in method item of Tensor object at 0x0000016EBC9DF7F0>:.4f
Epoch 800, Loss: <built-in method item of Tensor object at 0x0000016EBC9DF7F0>:.4f
Epoch 1000, Loss: <built-in method item of Tensor object at 0x0000016EBC9DE260>:.4f
Epoch 1200, Loss: <built-in method item of Tensor object at 0x0000016EBC9DE260>:.4f
Epoch 1400, Loss: <built-in method item of Tensor object at 0x0000016EBC9DF1B0>:.4f
Epoch 1600, Loss: <built-in method item of Tensor object at 0x0000016EBC9DF1B0>:.4f
Epoch 1800, Loss: <built-in method item of Tensor object at 0x0000016EBC9DE260>:.4f


In [52]:
test = torch.tensor([[2.0]])
print("Prediction:", model(test).item())
print("Actual:", 2.0**2)

Prediction: 4.259612083435059
Actual: 4.0


# 🧩 RNN (Recurrent Neural Network)

In [53]:
import torch
import torch.nn as nn
import torch.optim as optim

In [54]:
sequences = torch.tensor([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6]
], dtype=torch.float32)

targets = torch.tensor([[4], [5], [6], [7]], dtype=torch.float32)

# reshape to (batch, seq_len, features)
sequences = sequences.view(4, 3, 1)


In [55]:
# Build RNN Model
class SimpleRNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.rnn = nn.RNN(input_size=1, hidden_size=8, batch_first=True)
        self.fc = nn.Linear(8, 1)

    def forward(self, x):
        out, _ = self.rnn(x)          # RNN processes sequence
        last_out = out[:, -1, :]      # take last time step
        out = self.fc(last_out)       # map to output
        return out

model = SimpleRNN()


In [56]:
loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [57]:
for epoch in range(500):
    pred = model(sequences)
    loss = loss_fn(pred, targets)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print(epoch, loss.item())


0 38.34813690185547
50 3.676180362701416
100 1.214820146560669
150 1.1688661575317383
200 0.2783965468406677
250 0.06892208009958267
300 0.03281386196613312
350 0.012287240475416183
400 0.0037926321383565664
450 0.0009510623058304191


In [58]:
test = torch.tensor([[8, 9, 10]], dtype=torch.float32).view(1,3,1)
print(model(test))


tensor([[7.3169]], grad_fn=<AddmmBackward0>)


# 🧩 LSTM

In [59]:
import torch
import torch.nn as nn
import torch.optim as optim

In [60]:
sequences = torch.tensor([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
], dtype=torch.float32).view(4,3,1)

targets = torch.tensor([
    [4],
    [5],
    [6],
    [7]
], dtype=torch.float32)


In [61]:
# Build LSTM Model

class SimpleLSTM(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=1, hidden_size=16, batch_first=True)
        self.fc = nn.Linear(16,1)

    def forward(self, x):
        out, (h_n, c_n) = self.lstm(x)
        last_output = out[:, -1, :]
        out = self.fc(last_output)
        return out

model = SimpleLSTM()

In [62]:
loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [63]:
for epoch in range(500):
    pred = model(sequences)
    loss = loss_fn(pred, targets)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss {loss.item():.4f}")


Epoch 0, Loss 32.4640
Epoch 50, Loss 1.3298
Epoch 100, Loss 0.3852
Epoch 150, Loss 0.0045
Epoch 200, Loss 0.0000
Epoch 250, Loss 0.0000
Epoch 300, Loss 0.0000
Epoch 350, Loss 0.0000
Epoch 400, Loss 0.0000
Epoch 450, Loss 0.0000


In [64]:
test_seq = torch.tensor([[8, 9, 10]], dtype=torch.float32).view(1,3,1)
print("Prediction:", model(test_seq).item())
print("Expected:", 11)


Prediction: 7.250628471374512
Expected: 11


# PyTorch Muscle Training

In [65]:
import torch

x = torch.tensor([
    [1,2,3,4],
    [3,4,5,6],
    [5,6,7,8]
], dtype=torch.float32)

print("shape: ", x.shape)

shape:  torch.Size([3, 4])


In [66]:
device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = x.to(device)

In [67]:
x = x* 2
print("Tensor: ", x)
print("Device: ", device)

Tensor:  tensor([[ 2.,  4.,  6.,  8.],
        [ 6.,  8., 10., 12.],
        [10., 12., 14., 16.]])
Device:  cpu


In [68]:
x = torch.tensor(4.0, requires_grad=True)

y = 3*x**2+2*x

y.backward()

print("Gradient: ", x.grad)

Gradient:  tensor(26.)


In [69]:
x = torch.tensor(5.0, requires_grad=True)
y = 3*x**2

y.backward()

print("Gradient: ", x.grad)

Gradient:  tensor(30.)


In [70]:
for epoch in range(10):
    pred = model(x)
    loss = loss_fn(pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

ValueError: LSTM: Expected input to be 2D or 3D, got 0D instead

In [71]:
import torch.nn as nn
model  = nn.Sequential(
    nn.Linear(1, 8),
    nn.ReLU(),
    nn. Linear(8,1)
)

In [73]:
import torch
import torch.nn as nn
import torch.optim as optim

# Model
model = nn.Sequential(
    nn.Linear(1, 16),
    nn.ReLU(),
    nn.Linear(16, 1)
)

# Data
x = torch.tensor([[4.0]])
y = torch.tensor([[48.0]])  # 3*x^2 = 48

# Loss & Optimizer
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training
for epoch in range(100):
    pred = model(x)
    loss = loss_fn(pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(loss.item())


2236.39697265625
1755.2322998046875
1171.8070068359375
782.3077392578125
522.2747802734375
348.6748046875
232.77813720703125
155.4046630859375
103.74940490722656
69.263916015625


In [74]:
for name, param in model.named_parameters():
    print(name, param.grad.shape)


0.weight torch.Size([16, 1])
0.bias torch.Size([16])
2.weight torch.Size([1, 16])
2.bias torch.Size([1])


In [76]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(0)
X = torch.randn(200,2)
y = (X[:, 0] + X[:,1] >0 ).float().view(-1, 1)


In [83]:
model = nn.Sequential(
    nn.Linear(2,8),
    nn.ReLU(),
    nn.Linear(8,1),
    nn.Sigmoid()
)

In [84]:
loss_fn = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [86]:
for epoch in range(200):
    pred = model(X)
    loss = loss_fn(pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.7048
Epoch 20, Loss: 0.6829
Epoch 40, Loss: 0.6622
Epoch 60, Loss: 0.6425
Epoch 80, Loss: 0.6234
Epoch 100, Loss: 0.6048
Epoch 120, Loss: 0.5868
Epoch 140, Loss: 0.5691
Epoch 160, Loss: 0.5519
Epoch 180, Loss: 0.5351


In [87]:
with torch.no_grad():
    pred = model(X)
    predicted_classes = (pred > 0.5).float()
    accuracy = (predicted_classes == y).float().mean()

print("Accuracy:", accuracy.item())

Accuracy: 0.9599999785423279
